"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_comment)\
$os\
$username\
$hostname\
[](bg:color_purple fg:color_comment)\
$directory\
[](fg:color_purple bg:color_orange)\
$git_branch\
$git_status\
[](fg:color_orange bg:color_pink)\
$time\
[ ](fg:color_pink)\

$character"""

right_format = """$aws"""

palette = 'dracula'

[palettes.dracula]
color_fg = '#f8f8f2'
color_bg = '#282a36'
color_comment = '#6272a4'
color_cyan = '#8be9fd'
color_green = '#50fa7b'
color_orange = '#ffb86c'
color_pink = '#ff79c6'
color_purple = '#bd93f9'
color_red = '#ff5555'
color_yellow = '#f1fa8c'

[os]
disabled = false
style = "bg:color_comment fg:color_fg"

[os.symbols]
Macos = "󰀵"
Ubuntu = "󰕈"
Linux = "󰌽"
Windows = "󰍲"
Arch = "󰣇"
Debian = "󰣚"
Fedora = "󰣛"
Raspbian = "󰐿"
Amazon = ""

[username]
show_always = true
style_user = "bg:color_comment fg:color_fg"
style_root = "bg:color_comment fg:color_fg"
format = '[ $user ]($style)'

[hostname]
ssh_only = true
style = "bg:color_comment fg:color_fg"
format = '[@$hostname ]($style)'
ssh_symbol = '󰣀 '

[directory]
style = "fg:color_fg bg:color_purple"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bg:color_orange"
format = '[[ $symbol\( $branch\) ](fg:color_fg bg:color_orange)]($style)'

[git_status]
disabled = true

[nodejs]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol($version) ](fg:color_fg bg:color_cyan)]($style)'

[c]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol($version) ](fg:color_fg bg:color_cyan)]($style)'

[cpp]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol($version) ](fg:color_fg bg:color_cyan)]($style)'

[rust]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol($version) ](fg:color_fg bg:color_cyan)]($style)'

[golang]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol($version) ](fg:color_fg bg:color_cyan)]($style)'

[php]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol($version) ](fg:color_fg bg:color_cyan)]($style)'

[java]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol($version) ](fg:color_fg bg:color_cyan)]($style)'

[kotlin]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol($version) ](fg:color_fg bg:color_cyan)]($style)'

[haskell]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol($version) ](fg:color_fg bg:color_cyan)]($style)'

[python]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol($version) ](fg:color_fg bg:color_cyan)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_pink"
format = '[[ ♥ $time ](fg:color_fg bg:color_pink)]($style)'

[aws]
format = '[](fg:color_yellow)[ 󰸸 $profile(@$region) ](bg:color_yellow fg:color_bg)[](fg:color_yellow)'
symbol = '󰸸 '
style = ""


[character]
disabled = false
success_symbol = '[\$](bold fg:color_green)'
error_symbol = '[\$](bold fg:color_red)'
vimcmd_symbol = '[\$](bold fg:color_green)'
